### ISSUE TITLE
Crash after export

### ISSUE THREAD

**Issue by JamesHendrix11** [AnyOldName3/ModOrganizer-to-OpenMW#14]
The program crashes after I click the "export to openMW" option. Spefically, MO2 just closes and thats that. Can't see any of my ESMs in the normal openMW launcher. I do have opwnMW set as an executable that I can run through MO2 as well as the launcher. I put the plugins (both of them) from Modorganizer-to-OpenMW in MO2's plugins folder manually and can see the tool for exporting. I also experience crashes (but MO2) doesn't close if I try to run openMW through MO2, either by itself or through the launcher. As of now starting Openmwlauncher and OpenMW manually does nothing. I'm using modOrganizer 2.4.4 I have the python proxy enabled. I have now figured that a dialogue box should open after using the tool to determine the proper file path. It does not and has not ever popped up for me. I even tried putting the proper file path into the part of the python that mentions the dialogue and broke the tool until I removed what I put in the code. I have gotten MO2 back to its functional state but the plugin is still not working for me.

**Comment by AnyOldName3** [comment]
I'll need your MO2 log. If this were happening for everyone, then this wouldn't be the first I'm hearing about it, so I need to know what makes your setup different.

**Comment by JamesHendrix11** [comment]
Unfortunately the error didn't produce a log. The difference was my anti-virus which was blocking the program all weekend and decided to tell me today. I just ran the plugin successfully and I can see my mods in the normal openmw launcher without using MO2. everything seems to be working now. Normally when this happens I get a pop-up from my anti-virus right away whenever I install a new program/game.
