### ISSUE TITLE
Having trouble connecting the OpenMW plugin to Mod organizer

### ISSUE THREAD

**Issue by shongad** [AnyOldName3/ModOrganizer-to-OpenMW#21]
Every time I load up the mod organizer after transferring the OpenMW to MO2 files into the plugins I get an error message saying "failed to initialize plugin" "ModuleNotFoundError: No module named 'PyQt5'", not sure what to do to fix, all my attempts have not accomplished anything.

**Comment by AnyOldName3** [comment]
Have you tried reading? For example, reading any of https://github.com/AnyOldName3/ModOrganizer-to-OpenMW#note, the descriptions for the betas in https://github.com/AnyOldName3/ModOrganizer-to-OpenMW/releases, the sticky comment on the Nexus page, or the file descriptions on the Nexus page would be a good place to start.
